-- Update the admin password hash to match the JavaScript implementation
-- This ensures the hash in the database matches what the code generates
-- Password: SamCloud2024
-- Hash generated by: SHA-256("SamCloud2024")

UPDATE admins 
SET password = '7fc650b2a3b0ec30d832cff9d0334333c5602d83c0f357e2afac86bef35a4fba'
WHERE email = 'graphstats.pro@gmail.com';

-- If the admin doesn't exist yet, insert it
INSERT INTO admins (email, password)
VALUES ('graphstats.pro@gmail.com', '7fc650b2a3b0ec30d832cff9d0334333c5602d83c0f357e2afac86bef35a4fba')
ON CONFLICT (email) DO UPDATE 
SET password = EXCLUDED.password;
